environments:
  production: &production
    precompile_assets: true
    asset_roles:
      - :app
      - :app_master
      - :util
    copy_exclude:
      - .git
    branch: master
    migrate: false
    migration_command: rake db:migrate --trace
  staging: &staging
    precompile_assets: true
    asset_roles:
      - :app
      - :app_master
      - :util
    copy_exclude:
      - .git
    branch: staging
    migrate: false
    migration_command: rake db:migrate --trace
  staging_rails3:
    <<: *staging
