defaults:
  precompile_assets: true
  assets_strategy: cleaning
  asset_dependencies:
  - app/assets
  - vendor/assets
  - lib/assets
  copy_exclude:
  - .git
  migrate: false
  migration_command: rake db:migrate --trace
  asset_roles:
  - :app
  - :app_master
  - :util
environments:
  production:
    branch: master
  staging:
    branch: staging
