development:
  database: redu_development
  databases:
    vis:
      database: vis_development
test:
  database: redu_test
production:
  database: redu_production
  databases:
    vis:
      database: vis_production
